pipeline:
  name: delegate
  identifier: delegate
  projectIdentifier: RN
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: rngit
        repoName: delegate
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: wait for DIND
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      while ! docker ps ;do   
                            echo "Docker not available yet"  
                      done  
                      echo "Docker Service Ready"  
                      docker ps 
              - step:
                  type: Security
                  name: bandit
                  identifier: bandit
                  spec:
                    privileged: true
                    settings:
                      policy_type: orchestratedScan
                      scan_type: repository
                      product_name: bandit
                      product_config_name: default
                      repository_project: <+codebase.repoUrl>
                      repository_branch: "<+codebase.sourceBranch> "
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push an image to Docker Registry_1
                  identifier: BuildandPushanimagetoDockerRegistry_1
                  spec:
                    connectorRef: rndockerHub
                    repo: ryannelson01/delegate
                    tags:
                      - custom-<+pipeline.sequenceId>
          serviceDependencies:
            - identifier: DIND
              name: DIND
              type: Service
              spec:
                connectorRef: rndockerHub
                image: docker:dind
                privileged: true
          sharedPaths:
            - /var/run
            - /var/lib/docker
  variables: []
